all:
	g++ -std=c++11 -lpthread -o mutex mutex.cpp
	g++ -std=c++11 -lpthread -o spinlock spinlock.cpp
	g++ -std=c++11 -lpthread -o sem sem.cpp
	g++ -std=c++11 -lpthread -o homemade_spinlock homemade_spinlock.cpp
	g++ -std=c++11 -lpthread -o pi_free pi_free.cpp
	g++ -std=c++11 -lpthread -o pi_lock pi_lock.cpp
	g++ -std=c++11 -lpthread -o crossroad crossroad.cpp
mutex: mutex.cpp
		g++ -std=c++11 -lpthread -o mutex mutex.cpp
spinlock: spinlock.cpp
		g++ -std=c++11 -lpthread -o spinlock spinlock.cpp
sem: sem.cpp
		g++ -std=c++11 -lpthread -o sem sem.cpp
homemade_spinlock: homemade_spinlock.cpp
		g++ -std=c++11 -lpthread -o homemade_spinlock homemade_spinlock.cpp
pi_free: pi_free.cpp
		g++ -std=c++11 -lpthread -o pi_free pi_free.cpp
pi_lock: pi_lock.cpp
		g++ -std=c++11 -lpthread -o pi_lock pi_lock.cpp
crossroad: crossroad.cpp
		g++ -std=c++11 -lpthread -o crossroad crossroad.cpp
		
